server:
  port: 8080
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://AS-Test:test@population.yidl0.mongodb.net/Customer
      
  application:
    name: customer-service

    
eureka:
  instance:
    hostname: localhost