server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://AS-Test:test@population.yidl0.mongodb.net/Order
      
  application:
    name: order-service
    
eureka:
  instance:
    hostname: localhost